### ISSUE TITLE
Auto scroll resetting to the start when I set the text dynamically

### ISSUE THREAD

**Issue by SrujithPoondla** [minhtc/react-native-auto-scrolling#1]
If I set the text dynamically like the below example, then the animation is not smooth. Could you please guide what to change to get the animation smooth.

```
<Text style={styles.welcome}>{this.state.date.hour}</Text> ( the animation is not smooth, hour scrolls and then suddenly resets to the starting position)
```
_________
```
<Text style={styles.welcome}>hour</Text> (this works totally fine hour scrolls in a loop)
```

**Comment by maslhiro** [comment]
Me too, I think this component is not updating duration when changing text :( you can use **componentDidUpdate**  to fix it .
Sorry for my bad english

**Comment by cromatikap** [comment]
@maslhiro your english is totally fine :+1: 

Could you explain with more details how do you fix it? For me it seems that the problem come from the length of my prop that is changing. A way to fix it is to settle the size and center the content with `textAlign` but the effect is less interesting than the original demo.

Here is my code:
```
export class AdvertPictures extends React.Component {
  constructor(props){
    super(props)

    this.state = {
      currentIndex: 0
    }
  }

  render(){
    return(
      <View>
        <SliderBox
          images={this.props.images}
          onCurrentImagePressed={index => console.log(index)}
          currentImageEmitter={index => this.setState({currentIndex: index})}
          dotColor="red"
          inactiveDotColor="purple"
        />
        <AutoScrolling
          delay={0}
          duration={10000}
          endPaddingWidth={20}
        >
          <Text
            style={{
              color: this.props.colors.advertPicture,
              padding: 5,
              width: 1050,          // <- hacky fix
              textAlign: 'center'  // <- hacky fix
            }}
          >
            {this.props.adverts[this.state.currentIndex]}
          </Text>
        </AutoScrolling>
      </View>
    )
  }
}
```

For now I stick with this solution, but if you have a way to keep the size dynamic using `componentDidUpdate` please let me know :)

**Comment by minhtc** [comment]
@bidetaggle @maslhiro @SrujithPoondla I have just updated the new version (2.0) which I rewrote module in function component and using React hooks instead of PureComponent. 
Please help to check! Thank you.

**Comment by cromatikap** [comment]
Thank you very much! I test this tomorrow and I let you know!

**Comment by cromatikap** [comment]
@minhtc it works perfectly for me :1st_place_medal: , you can close the issue :+1:

**Comment by minhtc** [comment]
> @minhtc it works perfectly for me 🥇 , you can close the issue 👍

Many thanks.
