### ISSUE TITLE
Depreciation of the package

### ISSUE THREAD

**Issue by ItsMeSkink** [minhtc/react-native-auto-scrolling#19]
![image](https://user-images.githubusercontent.com/57059901/165604349-f6d994af-718e-4225-81b5-adeeefe80afd.png)
Dated 28th April, 2022, it is displaying that the package is depreciated. It would be of great help if anyone can share with me the occurred problem. 

Thanks

**Comment by minhtc** [comment]
Use this one instead: https://www.npmjs.com/package/@homielab/react-native-auto-scroll
