### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by JorgeArmandoMT** [minhtc/react-native-auto-scrolling#24]
How can I make it an infinite loop?

**Comment by minhtc** [comment]
> How can I make it an infinite loop?

It is infinite loop by default

**Comment by JorgeArmandoMT** [comment]
Thanks, I saw the demo on expo.io and it wasn't an infinite loop.

**Comment by JorgeArmandoMT** [comment]
For text I found another way to do it.

https://www.npmjs.com/package/react-native-text-ticker
