### ISSUE TITLE
contentRef.measure is not a function

### ISSUE THREAD

**Issue by engineerkv** [minhtc/react-native-auto-scrolling#3]
![Simulator Screen Shot - iPhone 8 Plus - 2020-04-06 at 12 28 47](https://user-images.githubusercontent.com/18220394/78531049-5df7a580-7802-11ea-97fe-2c8401c526a8.png)

**Comment by granitebps** [comment]
I got this problem too

**Comment by mickev36** [comment]
Wrap the content in a View, i had the same issue using a Flatlist Content, wrapping it in a View resolved the issue
