### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by SaeedZhiany** [minhtc/react-native-auto-scrolling#4]
Thanks for this library.

Is this library supports RTL direction applications? it can be very useful for marquee texts written in RTL language like Persian(Farsi).

**Comment by minhtc** [comment]
@SaeedZhiany  check out the latest version "react-native-auto-scrolling": "^2.1.0" supported isLTR

**Comment by olafkotur** [comment]
@SaeedZhiany RTL is supported by default, only pass `isLTR` if you want to override it
