### ISSUE TITLE
Could not resolve peer dependency react 16.9.0

### ISSUE THREAD

**Issue by HadrienPierart** [minhtc/react-native-auto-scrolling#7]
Hi,

Thanks a lot for the great library !
Could you fix your peer deps to at least allow minor versions upgrades of React ?
For instance, our project uses 16.13.1 which should be pretty close to 16.9 but the npm install breaks because of this peer dependency !

Thanks

**Comment by minhtc** [comment]
Checkout the latest version: "react-native-auto-scrolling": "^2.1.0"
BR
