### ISSUE TITLE
Metro encountered an error: this package specifies a `main` module field that could not be resolved

### ISSUE THREAD

**Issue by CostinBiserica** [minhtc/react-native-auto-scrolling#9]
Hello, I have installed this package and I get the following error:

`error: Metro has encountered an error: While trying to resolve module 'react-native-auto-scrolling' from file '.....\Home.js', the package '......\node_modules\react-native-auto-scrollinge\package.json' was successfully found. However, this package itself specifies a 'main' module field that could not be resolved ('......\node_modules\react-native-auto-scrollinge\dist\index.js'.`

I have tried to fix this by adding in the `metro.config.js` the following code:
`resolver: {                              
   sourceExts: ['jsx', 'js', 'ts', 'tsx'],
 },`

under `module.exports` (as I found that the Metrou doesn't know how to compile by default `.tsx`) but I still cannot use the package, as it returns me the same error when trying to run `react-native run-android`.

**Comment by wanjohiryan** [comment]
Just copy and paste the code from index.tsx in ". /src"

Two, you shouldn't be linking this package, it doesn't use any native code

**Comment by minhtc** [comment]
"react-native-auto-scrolling": "^3.0.0"

**Comment by minhtc** [comment]
Try to install the latest version "react-native-auto-scrolling": "^3.0.0"
